version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres        # Имя пользователя
      POSTGRES_PASSWORD: 123456 # Пароль
      POSTGRES_DB: pomodoro_tracker          # Имя базы данных
    ports:
      - "5432:5432"
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge